---
- name: Update Debian/Ubuntu system to specific release
  apt:
    name: "*"
    update_cache: yes
    autoclean: yes
    state: latest
    default_release: "{{ deb_release_ver }}"
    autoremove: "{{ autoremove_pkgs }}"
  when:
    - ansible_pkg_mgr == "apt" and deb_release_ver is defined
  register: update_result_apt
  until: update_result_apt is succeeded
  retries: 3

- name: Update Debian/Ubuntu system
  apt:
    name: "*"
    update_cache: yes
    autoclean: yes
    state: latest
    autoremove: "{{ autoremove_pkgs }}"
  when:
    - ansible_pkg_mgr == "apt" and deb_release_ver is not defined
  register: update_result_apt
  until: update_result_apt is succeeded
  retries: 3

- name: Smart reboot
  include_tasks: smart_reboot.yml
  when: smart_reboot_pkg is defined